# Generated by Django 5.2.9 on 2026-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0005_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_courses',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='courses.course', verbose_name='Ruxsat etilgan kurslar'),
        ),
    ]
