# Generated by Django 5.2.9 on 2026-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_allowed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_limit',
            field=models.IntegerField(default=0, help_text='0 = cheksiz', verbose_name="Kunlik dars ko'rish limiti"),
        ),
    ]
