# Generated by Django 5.2.9 on 2026-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Aktivlik zanjiri (kun)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi faoliyat sanasi'),
        ),
    ]
