# Generated by Django 5.2.9 on 2026-02-20 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_daily_streak_user_last_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name='Qurilma ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='Qurilma nomi')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzili')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'db_table': 'user_devices',
                'ordering': ['-last_login'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
