# Generated by Django 5.2.9 on 2026-02-19 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Kirish'), ('logout', 'Chiqish'), ('login_failed', 'Muvaffaqiyatsiz kirish'), ('video_access', "Video ko'rish"), ('video_upload', 'Video yuklash'), ('user_created', 'Foydalanuvchi yaratildi'), ('user_blocked', 'Foydalanuvchi bloklandi'), ('user_unblocked', 'Foydalanuvchi blokdan chiqarildi'), ('admin_action', 'Admin harakat'), ('suspicious', 'Shubhali harakat')], max_length=20, verbose_name='Harakat turi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name="Brauzer ma'lumoti")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xavfsizlik log',
                'verbose_name_plural': 'Xavfsizlik loglar',
                'db_table': 'security_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='security_lo_action_c2503a_idx'), models.Index(fields=['user', '-created_at'], name='security_lo_user_id_7828de_idx')],
            },
        ),
    ]
