# Generated by Django 5.2.9 on 2026-02-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_uz', models.CharField(default="Ingliz tilini biz bilan o'rganing", max_length=255)),
                ('hero_title_ru', models.CharField(default='Изучайте английский с нами', max_length=255)),
                ('hero_title_en', models.CharField(default='Learn English with us', max_length=255)),
                ('hero_description_uz', models.TextField(default='Tez, onson va samarali')),
                ('hero_description_ru', models.TextField(default='Быстро, легко и эффективно')),
                ('hero_description_en', models.TextField(default='Fast, easy and effective')),
                ('hero_bg_image', models.ImageField(blank=True, null=True, upload_to='cms/hero/')),
                ('hero_video_url', models.URLField(blank=True, help_text='YouTube or external video link', null=True)),
                ('features', models.JSONField(default=list, help_text='List of features: [{icon, title, desc}]')),
                ('cta_title_uz', models.CharField(default='Hoziroq boshlang', max_length=255)),
                ('cta_title_ru', models.CharField(default='Начните прямо сейчас', max_length=255)),
                ('cta_title_en', models.CharField(default='Start right now', max_length=255)),
                ('cta_link', models.CharField(default='/register', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Contents',
            },
        ),
    ]
