# Generated by Django 5.2.9 on 2026-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features Grid'), ('text_image', 'Text + Image'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('faq', 'FAQ Accordion'), ('custom', 'Custom HTML')], default='custom', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Internal title or section header', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Section',
                'verbose_name_plural': 'Landing Page Sections',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='LandingPageContent',
        ),
    ]
