# Generated by Django 5.2.9 on 2026-02-19 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'zbek)")),
                ('title_ru', models.CharField(max_length=255, verbose_name='Sarlavha (Rus)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Sarlavha (Ingliz)')),
                ('description_uz', models.TextField(blank=True, verbose_name="Tavsif (O'zbek)")),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Rus)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (Ingliz)')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=15, verbose_name='Daraja')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video fayl')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name="Oldindan ko'rish rasmi")),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (soniya)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
                'db_table': 'videos',
                'ordering': ['level', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name="Ko'rilgan vaqt (soniya)")),
                ('completed', models.BooleanField(default=False, verbose_name='Tugatilgan')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name="Oxirgi ko'rilgan vaqt")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video progress',
                'verbose_name_plural': 'Video progresslar',
                'db_table': 'video_progress',
                'ordering': ['-last_watched'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
