# Generated by Django 5.2.9 on 2026-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Rus)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name="Sarlavha (O'zbek)"),
        ),
    ]
