# Generated by Django 5.2.9 on 2026-02-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_video_title_ru_alter_video_title_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255, verbose_name="Sarlavha (O'zbek)")),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Rus)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Sarlavha (Ingliz)')),
                ('description_uz', models.TextField(blank=True, verbose_name="Tavsif (O'zbek)")),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Rus)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (Ingliz)')),
                ('course_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('other', 'Other')], default='standard', max_length=20, verbose_name='Kurs turi')),
                ('custom_course_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Boshqa tur (agar tanlangan bo'lsa)")),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='Kurs rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses',
            },
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Davomiyligi (soniya)'),
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course', verbose_name='Kurs'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField(verbose_name="Savol matni (O'zbek)")),
                ('text_ru', models.TextField(blank=True, verbose_name='Savol matni (Rus)')),
                ('text_en', models.TextField(blank=True, verbose_name='Savol matni (Ingliz)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(max_length=255, verbose_name="Variant matni (O'zbek)")),
                ('text_ru', models.CharField(blank=True, max_length=255, verbose_name='Variant matni (Rus)')),
                ('text_en', models.CharField(blank=True, max_length=255, verbose_name='Variant matni (Ingliz)')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
            },
        ),
    ]
