# Generated by Django 5.2.9 on 2026-02-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_alter_video_duration_seconds_video_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='telegram_group_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Telegram guruh havolasi'),
        ),
    ]
