# Generated by Django 5.2.9 on 2026-02-19 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_telegram_group_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveIntegerField(verbose_name="To'g'ri javoblar")),
                ('total_questions', models.PositiveIntegerField(verbose_name='Jami savollar')),
                ('score_percentage', models.FloatField(verbose_name='Foiz')),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sanasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='courses.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
