# Generated by Django 5.2.9 on 2026-02-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_en',
            field=models.CharField(blank=True, max_length=255, verbose_name="To'g'ri javob (EN)"),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name="To'g'ri javob (RU)"),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name="To'g'ri javob (UZ)"),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Multiple Choice'), ('text', 'Text Input')], default='choice', max_length=10, verbose_name='Savol turi'),
        ),
    ]
