# Generated by Django 5.2.9 on 2026-02-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_correct_answer_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Multiple Choice'), ('multi_choice', 'Multiple Answer'), ('text', 'Text Input'), ('true_false', 'True/False')], default='choice', max_length=20, verbose_name='Savol turi'),
        ),
    ]
