# Generated by Django 5.2.9 on 2026-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/', verbose_name='Video 1080p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p/', verbose_name='Video 480p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/', verbose_name='Video 720p'),
        ),
    ]
