# Generated by Django 5.2.9 on 2026-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_video_1080p_video_video_480p_video_video_720p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p/', verbose_name='Video 360p'),
        ),
    ]
