# Generated by Django 5.2.9 on 2026-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_video_video_360p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_1440p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1440p/', verbose_name='Video 1440p (2K)'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_2160p',
            field=models.FileField(blank=True, null=True, upload_to='videos/2160p/', verbose_name='Video 2160p (4K)'),
        ),
    ]
