# Generated by Django 5.2.9 on 2026-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_video_video_1440p_video_video_2160p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Transcoding holati'),
        ),
    ]
