# Generated by Django 5.2.9 on 2026-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_video_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='daily_limit',
            field=models.IntegerField(default=0, help_text='0 = cheksiz', verbose_name="Kunlik qo'shiq/dars ko'rish limiti"),
        ),
    ]
