# Generated by Django 5.2.9 on 2026-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weekly_days_limit',
            field=models.IntegerField(default=0, help_text="0 = cheksiz. Masalan 3 yozsangiz, foydalanuvchi haftasiga faqat 3 kun dars ko'ra oladi.", verbose_name="Haftalik dars ko'rish kunlari limiti"),
        ),
    ]
