# Generated by Django 5.2.9 on 2026-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_weekly_days_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='weekly_days_limit',
        ),
        migrations.AddField(
            model_name='course',
            name='allowed_days',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text="0=Dushanba, 1=Seshanba... 6=Yakshanba. Vergul bilan kengaytmada (masalan '0,2,4' = Du,Chor,Jum)", max_length=50, verbose_name='Ruxsat etilgan kunlar'),
        ),
    ]
